#shoes
shoes = [
    {name: 'Jimmy Choo ' 'Kendall' ' Crystal Pump', brand_id: 116, release_month: 'January', description: 'A scintillating mix of crystals casts flashbulb dazzle across a red carpet–ready pump, perched atop a slim heel. Jimmy Choo ' 'Kendall' ' Crystal Pump Jimmy Choo Jimmy Choo Pumps Shoes Approx. heel height: 5 3/4" with 1 1/2" platform (comparable to a 4 1/4" heel). Measurements taken from size 39 EU and may vary slightly by size. Metallic leather upper/leather lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/2/_7548482.jpg', price: '$2,995.00'},
    {name: 'Jimmy Choo ' 'Kera' ' Platform Sandal', brand_id: 116, release_month: 'February', description: 'Brilliant crystals dazzle the T-strap style of a scintillating platform sandal balanced by a slim, wrapped heel. Jimmy Choo ' 'Kera' ' Platform Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Approx. heel height: 4 1/4" with 1/2" platform. Measurements taken from size 39 EU and may vary slightly by size. Back zip closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/19/_7548379.jpg', price: '$2,195.00'},
    {name: 'Miu Miu Ankle Strap Platform Sandal', brand_id: 152, release_month: 'March', description: 'Miu Miu Ankle Strap Platform Sandal MIU MIU Miu Miu Sandals/Slides Shoes Adjustable strap with buckle closure. Approx. heel height: 5 1/4" with 1 3/4" platform (comparable to a 3 1/2" heel). Metallic leather upper/leather lining/rubber sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/11/_7389971.jpg', price: '$2,100.00'},
    {name: 'Jimmy Choo ' 'Kalpa' ' Sandal', brand_id: 116, release_month: 'April', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.Diminutive crystals trace the elegant lines of a plush suede sandal topped with a lofty, ankle-wrap strap. Jimmy Choo ' 'Kalpa' ' Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Approx. heel height: 5 1/2" with 1 1/2" platform (comparable to a 4" heel). Adjustable strap with buckle closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/1/_7605141.jpg', price: '$1,995.00'},
    {name: 'Brian Atwood ' 'Maia' ' Sandal', brand_id: 39, release_month: 'May', description: 'A radiant sculpture of mixed media creates a statement T-bar sandal balanced atop a slim heel and platform. Brian Atwood ' 'Maia' ' Sandal BRIAN ATWOOD Brian Atwood Sandals/Slides Shoes Approx. heel height: 6" with 1 1/2" platform (comparable to a 4 1/2" heel). Leather and genuine stingray upper/leather lining and sole. Salon Shoes. Made in Italy. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/12/_7397732.jpg', price: '$1,995.00'},
    {name: 'Old Gringo ' 'Diego Swarovski' ' Boot', brand_id: 170, release_month: 'June', description: 'Swarovski crystals trace a sparkling pattern on a Western-style boot handcrafted in antiqued leather. Old Gringo ' 'Diego Swarovski' ' Boot OLD GRINGO Old Gringo Boots Shoes Approx. heel height: 2' '. Approx. boot shaft height: 12 1/2"; 15" calf circumference. Leather upper, lining and sole. By Old Gringo; imported. BP. Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/7/_7461807.jpg', price: '$1,889.95'},
    {name: 'Prada Crystal Platform Sandal', brand_id: 183, release_month: 'July', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships. Prada Crystal Platform Sandal Prada Prada Sandals/Slides Shoes Adjustable strap with buckle closure. Approx. heel height: 4 1/2" with 1/2" platform. Silk and crystal upper/leather lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/12/_7414172.jpg', price: '$1,800.00'},
    {name: 'Sergio Rossi ' 'Mermaid' ' Bootie', brand_id: 207, release_month: 'August', description: 'Metallic leather waves dotted with Swarovski crystals create an airy sandal lifted by a super-slim wrapped heel. Sergio Rossi ' 'Mermaid' ' Bootie SERGIO ROSSI Sergio Rossi Sandals/Slides Shoes Back zip closure. Approx. heel height: 4". Leather upper, lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/15/_7354455.jpg', price: '$1,760.00'},
    {name: 'Prada Ankle Cuff Sandal', brand_id: 183, release_month: 'September', description: 'Prada Ankle Cuff Sandal Prada Prada Sandals/Slides Shoes Approx. heel height: 5 1/2" with 1 3/4" platform (comparable to a 3 3/4" heel). Back zip closure with adjustable strap. Suede upper/leather lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/11/_7631831.jpg', price: '$1,750.00'},
    {name: 'Charlotte Olympia ' 'Cherie' ' Sandal', brand_id: 45, release_month: 'October', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.A playful dose of je ne sais quoi charms a poodle-propped sandal cast in pale pink. Charlotte Olympia ' 'Cherie' ' Sandal CHARLOTTE OLYMPIA Charlotte Olympia Sandals/Slides Shoes Approx. heel height: 5 3/4" with 1 1/4" platform (comparable to a 4 1/2" heel). Adjustable strap with buckle closure. Patent leather upper/leather lining and sole. Imported. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/5/_7533925.jpg', price: '$1,695.00'},
    {name: 'Charlotte Olympia ' 'Parisienne' ' Sandal', brand_id: 45, release_month: 'November', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.A lithe, ankle-wrap strap tops off the crystalline decadence of an ethereally translucent sandal, sparkling with fairy-tale chic. Charlotte Olympia ' 'Parisienne' ' Sandal CHARLOTTE OLYMPIA Charlotte Olympia Pumps Shoes Adjustable strap with buckle closure. Approx. heel height: 4 1/4" with 1/2" platform. Synthetic upper/leather lining/synthetic sole. Made in Italy. Salon Shoes.', image_path: nil, price: '$1,695.00'},
    {name: 'Brian Atwood ' 'Tribeca Laser' ' Sandal', brand_id: 39, release_month: 'January', description: 'Diminutive studs trace the intricate waves of a sky-high, summer-breeze sandal. Brian Atwood ' 'Tribeca Laser' ' Sandal BRIAN ATWOOD Brian Atwood Sandals/Slides Shoes Approx. heel height: 6" with 1 1/2" platform (comparable to a 4 1/2" heel). Suede upper/leather lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/16/_7397736.jpg', price: '$1,695.00'},
    {name: 'Sergio Rossi ' 'Mermaid' ' Caged Sandal', brand_id: 207, release_month: 'January', description: 'Suede waves dotted with Swarovski crystals create an airy sandal lifted by a super-slim wrapped heel. Sergio Rossi ' 'Mermaid' ' Caged Sandal SERGIO ROSSI Sergio Rossi Sandals/Slides Shoes Back zip closure. Approx. heel height: 4". Suede, satin and Swarovski crystal upper/leather lining and sole. Imported. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/2/_7354422.jpg', price: '$1,670.00'},
    {name: 'Valentino ' 'Camo Rockstud' ' Pump', brand_id: 244, release_month: 'February', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.Golden pyramid studs glint on the caged straps of a crystallized leather pump with a slim heel and pointed toe. Valentino ' 'Camo Rockstud' ' Pump VALENTINO Valentino Pumps Shoes Approx. heel height: 4". Adjustable strap with buckle closure. Leather upper, lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/10/_7491570.jpg', price: '$1,595.00'},
    {name: 'Valentino ' 'Camo Rockstud' ' Flat', brand_id: 244, release_month: 'March', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.Pyramid studs amp up the edgy vibe of a pointy flat aglow with glittering crystals. Valentino ' 'Camo Rockstud' ' Flat VALENTINO Valentino Flats Shoes Leather upper, lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/16/_7642656.jpg', price: '$1,595.00'},
    {name: 'Sergio Rossi ' 'Murmansk' ' Sandal', brand_id: 207, release_month: 'April', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.Midnight crystals and starlight sparkle mingle atop the impeccable architecture of a curvaceous sandal, balanced atop a slim, satin heel. Sergio Rossi ' 'Murmansk' ' Sandal SERGIO ROSSI Sergio Rossi Sandals/Slides Shoes Approx. heel height: 4". Adjustable strap with buckle closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/10/_7532370.jpg', price: '$1,595.00'},
    {name: 'Lanvin Lucite® Wedge Sandal', brand_id: 134, release_month: 'May', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.A contemporary slice of Lucite® heightens the modern appeal of a scalloped suede sandal for head-turning impact. Lanvin Lucite® Wedge Sandal LANVIN Lanvin Sandals/Slides Shoes Adjustable strap with buckle closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/15/_7351975.jpg', price: '$1,590.00'},
    {name: 'Lanvin Pointy Toe Python Pump', brand_id: 134, release_month: 'June', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.High-impact iridescence ignites the razor-sharp silhouette of a hidden-platform pump perched on a sleek, silvery heel. Lanvin Pointy Toe Python Pump LANVIN Lanvin Pumps Shoes Approx. heel height: 5" with 1" platform (comparable to a 4" heel). Adjustable strap with buckle closure. Genuine python upper/leather lining and sole. Imported. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/0/_7635280.jpg', price: '$1,550.00'},
    {name: 'Lanvin Metal Heel Boot', brand_id: 134, release_month: 'July', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.A gilded heel elevates the structured personality of a prim platform boot with a chic pointy toe. Lanvin Metal Heel Boot LANVIN Lanvin Boots Shoes Approx. heel height: 5" with 1" platform (comparable to a 4" heel). Side zip closure. Leather upper, lining and sole. Imported. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/3/_7601543.jpg', price: '$1,550.00'},
    {name: 'Gucci ' 'Noah' ' Crystal d' 'Orsay Pump', brand_id: 95, release_month: 'August', description: 'Shimmering crystals illuminate a half d' 'Orsay pump with black-tie refinement. Gucci ' 'Noah' ' Crystal d' 'Orsay Pump Gucci Gucci Pumps Shoes Approx. heel height: 4 1/4". Satin upper/leather lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/15/_7403795.jpg', price: '$1,550.00'},
    {name: 'Old Gringo ' 'Eagle Swarovski' ' Boot', brand_id: 170, release_month: 'September', description: 'Swarovski crystals trace a sparkling pattern on a Western-style boot handcrafted in exceptionally soft leather. Old Gringo ' 'Eagle Swarovski' ' Boot OLD GRINGO Old Gringo Boots Shoes Pull-on style. Approx. heel height: 1 1/2". Approx. boot shaft height: 12 1/2"; 14" calf circumference. Leather upper, lining and sole. By Old Gringo; imported. BP. Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/13/_6255893.jpg', price: '$1,549.95'},
    {name: 'Jimmy Choo ' 'Kalpa' ' Sandal', brand_id: 116, release_month: 'October', description: 'Radiant snakeskin shimmers across the scintillating height of a fiercely feminine, ankle-strap sandal. Jimmy Choo ' 'Kalpa' ' Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Adjustable strap with buckle closure. Leather upper, lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/19/_7499939.jpg', price: '$1,495.00'},
    {name: 'Jimmy Choo ' 'Lola' ' Ankle Strap Sandal', brand_id: 116, release_month: 'November', description: 'Fierce florals paint the exotic texture of a snakeskin sandal balanced atop a slim heel and generous platform. Jimmy Choo ' 'Lola' ' Ankle Strap Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Adjustable strap with buckle closure. Approx. heel heigth: 5 1/2" with 1 1/2" platform (comparable to a 4" heel). Leather and synthetic upper/leather lining and sole. Made in Italy. Salon Shoes. ', image_path: nil, price: '$1,495.00'},
    {name: 'Charlotte Olympia ' 'Priscilla' ' Genuine Python Pump', brand_id: 45, release_month: 'January', description: 'Pre-order this style today! Add to Shopping Bag to view approximate ship date. You' 'll be charged only when your item ships.Exotic python and exuberant emerald take a signature pump to exhilarating heights of style. Charlotte Olympia ' 'Priscilla' ' Genuine Python Pump CHARLOTTE OLYMPIA Charlotte Olympia Pumps Shoes Approx. heel height: 5 3/4" with 1 1/2" platform (comparable to a 4 1/4" heel). Genuine python upper/leather lining and sole. Made in Italy. Salon Shoes.', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/6/_7469486.jpg', price: '$1,495.00'},
    {name: 'Jimmy Choo ' 'Diva' ' Sandal', brand_id: 116, release_month: 'January', description: 'Scintillating architecture and precision-set crystals create captivating after-dark sparkle on a cut-out, champagne sandal. Jimmy Choo ' 'Diva' ' Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Back zip closure. Approx. heel height: 5" with 3/4" platform. Leather upper, lining and sole. Made in Italy. Salon Shoes. ', image_path: 'http://content.nordstrom.com/ImageGallery/store/product/Thumbnail/12/_7383352.jpg', price: '$1,495.00'}
]

Shoe.create(shoes)

#brands
brands = [
    {name: '7 For All Mankind®'},
    {name: 'Acorn'},
    {name: 'Aetrex'},
    {name: 'Ahnu'},
    {name: 'Alegria'},
    {name: 'Alexander McQueen'},
    {name: 'Alexandre Birman'},
    {name: 'Alberto Fermani'},
    {name: 'Alberto Gozzi'},
    {name: 'Alice + Olivia'},
    {name: 'Andre Assous'},
    {name: 'Anyi Lu'},
    {name: 'ALDO'},
    {name: 'Aquatalia by Marvin K'},
    {name: 'Aravon'},
    {name: 'Arche'},
    {name: 'Ariat'},
    {name: 'Ash'},
    {name: 'ASICS®'},
    {name: 'Athena Alexander'},
    {name: 'Attilio Giusti Leombruni'},
    {name: 'B Brian Atwood'},
    {name: 'Badgley Mischka'},
    {name: 'BC Footwear'},
    {name: 'BCBGeneration'},
    {name: 'BCBGMAXAZRIA'},
    {name: 'Bed Stu'},
    {name: 'Bernardo'},
    {name: 'Betsey Johnson'},
    {name: 'Biala'},
    {name: 'Bionda Castana'},
    {name: 'Birkenstock'},
    {name: 'Birki' 's®'},
    {name: 'Blondo'},
    {name: 'Bogs'},
    {name: 'Børn'},
    {name: 'Boutique 9'},
    {name: 'BP.'},
    {name: 'Brian Atwood'},
    {name: 'Brooks'},
    {name: 'Burberry'},
    {name: 'Callisto'},
    {name: 'Calvin Klein'},
    {name: 'Charles by Charles David'},
    {name: 'Charlotte Olympia'},
    {name: 'Chinese Laundry'},
    {name: 'Chloé'},
    {name: 'Civic Duty'},
    {name: 'Clarks®'},
    {name: 'Classiques Entier®'},
    {name: 'COACH'},
    {name: 'Cobb Hill'},
    {name: 'Cole Haan'},
    {name: 'Converse'},
    {name: 'Cordani'},
    {name: 'Corso Como'},
    {name: 'Cushe'},
    {name: 'Dana Davis'},
    {name: 'Dansko'},
    {name: 'Delman'},
    {name: 'Dezario'},
    {name: 'Diane von Furstenberg'},
    {name: 'DKNYC'},
    {name: 'DolceGabbana'},
    {name: 'Dolce Vita'},
    {name: 'Donald J Pliner'},
    {name: 'Dr. Martens'},
    {name: 'DV by Dolce Vita'},
    {name: 'Earth®'},
    {name: 'Earthies®'},
    {name: 'ECCO'},
    {name: 'Eileen Fisher'},
    {name: 'Elie Tahari'},
    {name: 'Elizabeth and James'},
    {name: 'Emilio Pucci'},
    {name: 'Enzo Angiolini'},
    {name: 'Eric Michael'},
    {name: 'Ettore Masotti'},
    {name: 'Everybody'},
    {name: 'Fendi'},
    {name: 'Fergie'},
    {name: 'Fidji'},
    {name: 'Finn Comfort'},
    {name: 'FitFlop'},
    {name: 'Flounce'},
    {name: 'Franco Sarto'},
    {name: 'French Sole'},
    {name: 'Frye'},
    {name: 'Gentle Souls'},
    {name: 'Geox'},
    {name: 'Giuseppe Zanotti'},
    {name: 'Giesswein'},
    {name: 'Glint'},
    {name: 'Golden Goose'},
    {name: 'Gucci'},
    {name: 'GUESS'},
    {name: 'Haflinger'},
    {name: 'Halogen®'},
    {name: 'Havaianas'},
    {name: 'Helle Comfort'},
    {name: 'Helly Hansen'},
    {name: 'Hinge'},
    {name: 'House of Harlow 1960'},
    {name: 'Hunter'},
    {name: 'Icon Footwear'},
    {name: 'Isaac Mizrahi New York'},
    {name: 'Isola'},
    {name: 'Ivanka Trump'},
    {name: 'J. Reneé'},
    {name: 'Jack Rogers'},
    {name: 'Jacques Levine'},
    {name: 'Jambu'},
    {name: 'Jason Wu'},
    {name: 'Jeffrey Campbell'},
    {name: 'Jessica Simpson'},
    {name: 'Jimmy Choo'},
    {name: 'Joan  David'},
    {name: 'Joe' 's'},
    {name: 'Josef Seibel'},
    {name: 'Juicy Couture'},
    {name: 'K Jacques St. Tropez'},
    {name: 'Kalso Earth®'},
    {name: 'Kamik'},
    {name: 'kate spade new york'},
    {name: 'Keds®'},
    {name: 'Keen'},
    {name: 'Kelsi Dagger'},
    {name: 'Kickers'},
    {name: 'Kork-Ease'},
    {name: 'KORS Michael Kors'},
    {name: 'L.A.M.B.'},
    {name: 'L.K. Bennett'},
    {name: 'La Canadienne'},
    {name: 'Lanvin'},
    {name: 'Le Chameau'},
    {name: 'Lucky Brand'},
    {name: 'Manolo Blahnik'},
    {name: 'MARC BY MARC JACOBS'},
    {name: 'Mark  James by Badgley Mischka'},
    {name: 'Martino'},
    {name: 'Matiko'},
    {name: 'Matisse'},
    {name: 'Matt Bernson'},
    {name: 'Me Too'},
    {name: 'Mel by Melissa'},
    {name: 'Mephisto'},
    {name: 'Merrell'},
    {name: 'MIA'},
    {name: 'MICHAEL Michael Kors'},
    {name: 'Minnetonka'},
    {name: 'Miss Trish'},
    {name: 'Miu Miu'},
    {name: 'Miz Mooz'},
    {name: 'Mizuno'},
    {name: 'MM6 Maison Martin Margiela'},
    {name: 'Moschino Cheap  Chic'},
    {name: 'Munro'},
    {name: 'N.Y.L.A.'},
    {name: 'Naot'},
    {name: 'Naturalizer'},
    {name: 'Naughty Monkey'},
    {name: 'Naya'},
    {name: 'Nelly Venturi'},
    {name: 'New Balance'},
    {name: 'Nicholas Kirkwood'},
    {name: 'Nike'},
    {name: 'Nina'},
    {name: 'Nine West'},
    {name: 'North Face'},
    {name: 'Old Gringo'},
    {name: 'OluKai'},
    {name: 'Onex'},
    {name: 'Oscar de la Renta'},
    {name: 'OTBT'},
    {name: 'Patagonia'},
    {name: 'Paul Green'},
    {name: 'Pedro Garcia'},
    {name: 'Pelle Moda'},
    {name: 'PIKOLINOS'},
    {name: 'Poetic Licence'},
    {name: 'Pollini'},
    {name: 'Pour la Victoire'},
    {name: 'Prada'},
    {name: 'PUMA'},
    {name: 'Rachel Roy'},
    {name: 'Rachel Zoe'},
    {name: 'rag  bone'},
    {name: 'Rainbow'},
    {name: 'Ralph Lauren Collection'},
    {name: 'Rebecca Minkoff'},
    {name: 'RED Valentino'},
    {name: 'Reed Krakoff'},
    {name: 'Reef'},
    {name: 'REPORT'},
    {name: 'Robert Clergerie'},
    {name: 'Robert Zur'},
    {name: 'Romika'},
    {name: 'Ron White'},
    {name: 'Rosegold'},
    {name: 'Roxy'},
    {name: 'Saint Laurent'},
    {name: 'Salvatore Ferragamo'},
    {name: 'Sam Edelman'},
    {name: 'Saucony'},
    {name: 'Sbicca'},
    {name: 'See by Chloé'},
    {name: 'Sergio Rossi'},
    {name: 'Seychelles'},
    {name: 'Skemo'},
    {name: 'Söfft'},
    {name: 'Softspots'},
    {name: 'SoftWalk®'},
    {name: 'Sole Goddess®'},
    {name: 'Sole Society'},
    {name: 'Sorel'},
    {name: 'Sperry Top-Sider®'},
    {name: 'Splendid'},
    {name: 'Stella McCartney'},
    {name: 'Steve Madden'},
    {name: 'Steven by Steve Madden'},
    {name: 'Stuart Weitzman'},
    {name: 'Superga'},
    {name: 'Sweet Ballerina'},
    {name: 'Tabitha Simmons'},
    {name: 'Taccetti'},
    {name: 'Tecnica®'},
    {name: 'Ted Baker London'},
    {name: 'Teva'},
    {name: 'The North Face'},
    {name: 'Tildon'},
    {name: 'Think!'},
    {name: 'Timberland'},
    {name: 'TKEES'},
    {name: 'Tod' 's'},
    {name: 'TOMS'},
    {name: 'Topshop'},
    {name: 'Tory Burch'},
    {name: 'Tracy Reese'},
    {name: 'Trotters'},
    {name: 'Trouvé'},
    {name: 'Truth or Dare by Madonna'},
    {name: 'Tsubo'},
    {name: 'UGG® Australia'},
    {name: 'Valentino'},
    {name: 'VANELi'},
    {name: 'Vans'},
    {name: 'VC Signature'},
    {name: 'Vera Wang'},
    {name: 'Via Spiga'},
    {name: 'Vince'},
    {name: 'Vince Camuto'},
    {name: 'Yves Saint Laurent'},
    {name: 'Zadig  Voltaire'}
]

Brand.create(brands)

